### ISSUE TITLE
Question: Why not using stub files? (.pyi)

### ISSUE THREAD

**Issue by Diogo-Rossi** [haiiliin/pyabaqus#19]
Since some function files has only type hints, why not use stub `.pyi` for that files?

This could lead to 2 improvements:
* Differentiate files with code from that only with annotations 
* Suppress warnings when writing the type hints

BTW: Thank you for making this project.

**Comment by haiiliin** [comment]
Great idea. The problem is that just some functions are just for type hints, but for some functions such as creating a step, we actually need to create a Step object and append to the Model object.

**Comment by Diogo-Rossi** [comment]
Maybe there is another approach to suppress some warnings in type checker when writing the type hints,
even in common`.py` files.

By using ellipsis `...` instead of `pass`, the type checker does not complain anymore.

![image](https://user-images.githubusercontent.com/57204023/183900841-aaa57733-11ae-4e6e-a5c0-e930a92cf101.png)

In this case, I'm using [pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance)

![image](https://user-images.githubusercontent.com/57204023/183901138-f533cdee-4ccc-451a-8d78-e8a7b95b20e1.png)

**Comment by haiiliin** [comment]
Great idea! Maybe we can replace all the pass statement to ..., and also add some comments such as TODO to indicatethat it should be inplemented later on.
