### ISSUE TITLE
Conda Integration

### ISSUE THREAD

**Issue by Deliangus** [haiiliin/pyabaqus#2]
Drafted an conda integration solution, hope to help.

**Comment by Deliangus** [comment]
package:
  name: pyabaqus
  version: 1.0.14

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True # [py<37]

source:
  git_url: https://github.com/Haiiliin/pyabaqus.git
  git_rev: "V1.0.14"

requirements:
  build:
    - python
  run:
    - python
    - "pyqt5 >=5.15.6"
    - pandas
    - "qtpy >=2.0.1"

test:
  import:
    - abaqus
    - mesh
    - abaqusConstants
about:
  home: https://github.com/Haiiliin/pyabaqus
  license: MIT
# conda build pyabaqus -c default -c deliangus

**Comment by Deliangus** [comment]
[meta.zip](https://github.com/haiiliin/pyabaqus/files/8491082/meta.zip)

**Comment by Deliangus** [comment]
Check anaconda channel deliangus for pyabaqus package and its dependence packages

**Comment by haiiliin** [comment]
> Check anaconda channel deliangus for pyabaqus package and its dependence packages

pyabaqus is already uploaded to anaconda, thanks for your help.
